name: sync-TechXueXi/TechXueXi

on:
  schedule:
  - cron:  "*/15 * * * *"
  workflow_dispatch:
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id
    timeout-minutes: 2

    steps:
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y
        sudo -E apt-get install -y build-essential git git-core curl wget
        sudo -E apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'

    - name: Prepare
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.LXKEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com > ~/.ssh/known_hosts

    - name: Clone Master
      run: |
        git clone -b master https://github.com/TechXueXi/TechXueXi.git master

    - name: Push Master
      uses: ad-m/github-push-action@master
      with:
        directory: master
        github_token: ${{ secrets.PAT }}
        branch: master

    - name: Clone Dev
      run: |
        git clone -b dev https://github.com/TechXueXi/TechXueXi.git dev

    - name: Push Dev
      uses: ad-m/github-push-action@master
      with:
        directory: dev
        github_token: ${{ secrets.PAT }}
        branch: dev
        
    - name: Clone Dev-mg
      run: |
        git clone -b dev-mg https://github.com/TechXueXi/TechXueXi.git dev-mg

    - name: Push Dev-mg
      uses: ad-m/github-push-action@master
      with:
        directory: dev-mg
        github_token: ${{ secrets.PAT }}
        branch: dev-mg

    # - name: Delete Workflow Runs
      # uses: Mattraks/delete-workflow-runs@main
      # with:
        # token: ${{ github.token }}
        # repository: ${{ github.repository }}
        # retain_days: 1
        # keep_minimum_runs: 0
